AWSTemplateFormatVersion: 2010-09-09
Description: |
  AWS CloudFormation template to create a AWS-DMS Replication Instance Exiting Infra
  This playbook Created by Singaravelan.P @ Minfy Technologies
Parameters:

  VPC:
    Description: Enter the name of the VPC
    Default: 'vpc-c34870ab'
    Type: String
    
  DBSubnet1:
    Description: Enter the subnetid-1 on which the DMS replication instance will be placed
    Default: 'subnet-8a9eb8e2'
    Type: String
    
  DBSubnet2:
    Description: >-
      Enter the subnetid-2 on which the DMS replication instance will be placed,
      For high availability
    Default: 'subnet-976afddb'
    Type: String
    
  DMSReplicationInstanceClass:
    Description: Enter the DMS replication instance class
    Default: 'dms.t2.micro'
    Type: String
    ConstraintDescription: e.g. dms.t2.small
    AllowedValues:
      - dms.t2.micro
      - dms.t2.small
      - dms.t2.medium
      - dms.t2.large
      - dms.c4.large
      - dms.c4.xlarge
      - dms.c4.2xlarge
      - dms.c4.4xlarge
      - dms.r4.large
      - dms.r4.xlarge
      - dms.r4.2xlarge
      - dms.r4.4xlarge
      - dms.r4.8xlarge
      
  DMSReplicationInstanceidentifier:
    Description: Enter an id for the new DMS replication instance
    Default: Etechbrain-DB-Migration
    Type: String
    
  DMSSecurityGroup:
    Description: >-
      Enter the name of the security group that allows access to source and
      target.
    Type: String
    Default: 'sg-c8dbeda7'

  MultiAZ:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  PubliclyAccessible:
    Description: DMS will assign a public IP address to your replication instance, and you'll be able to connect to databases outside.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  EngineVersion: 
    Description: Choose an AWS DMS version to run on your replication instance.
    Type: String
    Default: '3.1.4'
    AllowedValues:
      - 2.4.4
      - 2.4.5
      - 3.1.3
      - 3.1.4
      - 3.3.0

  AllowMajorVersionUpgrade:
    Description: Choose whether you want AWS DMS to apply minor engine version upgrades to your replication instance
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  AllocatedStorage:
    Description: Must contain only numberic and min 20 GB & Max 6000 GB.
    Type: Number
    Default: '20'
    MaxValue: '6000'
    MinValue: '20'

  AvailabilityZone:
    Description: Choose an availability zone (AZ) where you want your replication instance to run
    Default: 'ap-south-1a'
    Type: String
    AllowedValues:
    - ap-south-1a
    - ap-south-1b
    - ap-south-1c 
    
Resources:

  DMSReplicationSubnetGroup:
    Type: 'AWS::DMS::ReplicationSubnetGroup'
    Properties:
      ReplicationSubnetGroupDescription: Subnets available for DMS
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
        
  DMSReplicationInstance:
    Type: 'AWS::DMS::ReplicationInstance'
    DependsOn:
      - DMSReplicationSubnetGroup
    Properties:
      PubliclyAccessible: !Ref PubliclyAccessible
      ReplicationInstanceClass: !Ref DMSReplicationInstanceClass
      EngineVersion: !Ref EngineVersion
      MultiAZ: !Ref MultiAZ
      AvailabilityZone: !Ref AvailabilityZone
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      ReplicationInstanceIdentifier: !Ref DMSReplicationInstanceidentifier
      ReplicationSubnetGroupIdentifier: !Ref DMSReplicationSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DMSSecurityGroup
        
Outputs:

  StackName:
    Value: !Ref 'AWS::StackName'
    
  RegionName:
    Value: !Ref 'AWS::Region'
    
  DMSReplicationInstanceArn:
    Value: !Ref DMSReplicationInstance
  
  DMSReplicationInstancePrivateIp:
    Value: !GetAtt DMSReplicationInstance.ReplicationInstancePrivateIpAddresses
  
  DMSReplicationInstancePublicIp:
    Value: !GetAtt DMSReplicationInstance.ReplicationInstancePublicIpAddresses