---
AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation script provisions a RDS instance.

Parameters:

  DBInstanceIdentifier:
    Description: Database Instance Identifier
    Type: String
    Default: 'etechbrainmssql'
    
  AllocatedStorage:
    Description: The allocated storage size, specified in gigabytes (GB).
    Type: String
    Default: '20'
    AllowedPattern: "^([2-9]?[0-9]{1}|[0-9]{3,4}|1[0-5]?[0-9]{3}|16[0-2]?[0-9]{2}|163[0-7]?[0-9]{1}|1638[0-4]?)$"
    ConstraintDescription: "For SQL Server Express or Web Edition, the value must be a valid number between 20-16384. For SQL Server Standard or Enteprise editions, the value must be a valid number between 200 and 16384"
  
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that's different from the DB instance's current major version, set this property to true.
    Type: String
    Default: 'true'
    AllowedValues: 
      - true
      - false
    ConstraintDescription: "Value must be boolean value."

  AutoMinorVersionUpgrade:
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    Default: 'true'
    AllowedValues: 
      - true
      - false
    ConstraintDescription: "Value must be boolean value."
  
  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
    Type: String
    Default: '7'
    AllowedPattern: "^([0-9]{1}|[1-2]{1}[0-9]{1}|3[0-5]{1})$"
    ConstraintDescription: "Value must be a valid number between 0-35."

  DBPreferredBackupWindow:
    Description: DB Preferred Backup Window
    Type: String
    Default: '02:00-03:00'
  
  DBPreferredMaintenanceWindow:
    Description: DB Preferred Maintenance Window
    Type: String
    Default: 'sun:03:00-sun:04:00'
    
  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: 'db.r4.large'
    AllowedValues:
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
      
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: sqlserver-se
    AllowedValues:
      - sqlserver-ee
      - sqlserver-se
      - sqlserver-ex
      - sqlserver-web
    ConstraintDescription: "Please specify either a sqlserver-ee, sqlserver-se, sqlserver-ex, or sqlserver-web engine for the RDS instance."

  DBSubnet1:
    Description: A DB subnet group to associate with the DB instance. 
    Type: String
    Default: 'subnet-0b233bd97ce8b9c1d'

  DBSubnet2:
    Description: A DB subnet group to associate with the DB instance. 
    Type: String
    Default: 'subnet-08d0020268f40ada1'
    
  VPCSecurityGroups:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: "Please provide valid ids for the security group(s)."

  MasterUsername:
    Description: The master user name for the DB instance.
    Type: String
    Default: 'etechadmin'

  MasterUserPassword:
    Description: The master password for the DB instance.
    Type: String
    Default: 'cloudredhat'
    NoEcho: true
    
  DBPubliclyAccessible:
    Description: Publicly Accessible
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
      
  MultiAZ:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: String
    Default: true
    AllowedValues: 
      - true
      - false
    ConstraintDescription: "Value must be boolean value."

Conditions:
 
  CreateSQLServerEnterpriseOrStandardResources: !Or  [!Equals [ !Ref Engine ,  sqlserver-ee], !Equals [ !Ref Engine ,  sqlserver-se]]
  CreateSQLServerExpressOrWebResources: !Not [!Or  [!Equals [ !Ref Engine ,  sqlserver-ee], !Equals [ !Ref Engine ,  sqlserver-se]]]

Resources:

  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB subnet group.
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
        
  SQLServerInstanceHigherEditions:
    Type: "AWS::RDS::DBInstance"
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      PreferredBackupWindow: !Ref DBPreferredBackupWindow
      PreferredMaintenanceWindow: !Ref DBPreferredMaintenanceWindow
      BackupRetentionPeriod:  !Ref BackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      LicenseModel: license-included
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups: !Ref VPCSecurityGroups
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MultiAZ: !Ref MultiAZ
      MonitoringInterval: 0
      PubliclyAccessible: !Ref DBPubliclyAccessible
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref Engine }
 
  SQLServerInstanceLowerEditions:
    Type: "AWS::RDS::DBInstance"
    Condition: CreateSQLServerExpressOrWebResources
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      PreferredBackupWindow: !Ref DBPreferredBackupWindow
      PreferredMaintenanceWindow: !Ref DBPreferredMaintenanceWindow
      BackupRetentionPeriod:  !Ref BackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      LicenseModel: license-included
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups: !Ref VPCSecurityGroups
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MonitoringInterval: 0
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: !Ref DBPubliclyAccessible 
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref Engine }

Outputs:

  DBInstanceIdentifierHigherEditions:
    Description: The database instance identifier
    Value: !Ref SQLServerInstanceHigherEditions
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Export:
      Name: !Sub 
      - "${AWS::StackName}-${engine}-identifier"
      - {engine: !Ref Engine }

  DBEndpointHigherEditions:
    Description: The connection endpoint for the database.
    Value: !GetAtt  SQLServerInstanceHigherEditions.Endpoint.Address
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-endpoint"
        - {engine: !Ref Engine }

  DBPortHigherEditions:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  SQLServerInstanceHigherEditions.Endpoint.Port
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-port"
        - {engine: !Ref Engine }

  DBInstanceIdentifierLowerEditions:
    Description: The database instance identifier
    Value: !Ref SQLServerInstanceLowerEditions
    Condition: CreateSQLServerExpressOrWebResources
    Export:
      Name: !Sub 
      - "${AWS::StackName}-${engine}-identifier"
      - {engine: !Ref Engine }

  DBEndpointLowerEditions:
    Description: The connection endpoint for the database.
    Value: !GetAtt  SQLServerInstanceLowerEditions.Endpoint.Address
    Condition: CreateSQLServerExpressOrWebResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-endpoint"
        - {engine: !Ref Engine }

  DBPortLowerEditions:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  SQLServerInstanceLowerEditions.Endpoint.Port
    Condition: CreateSQLServerExpressOrWebResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-port"
        - {engine: !Ref Engine }