AWSTemplateFormatVersion: 2010-09-09
Resources:
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: t2.micro
      KeyName: cfn-key-1
