AWSTemplateFormatVersion: "2010-09-09"
Resources:

  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: t2.micro
      KeyName: cfn-key-1
      SecurityGroups:
        - Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

  EIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Instance
    