AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  MyKeyName:
    Description: Select you keypair
    Type: AWS::EC2::KeyPair::KeyName

  MyAvailabilityZone:
    Description: Selec the AZ
    Type: String
    Default: ap-south-1b
    AllowedValues:
      - ap-south-1a
      - ap-south-1b 
      - ap-south-1c
  
  MyInstanceType:
    Description: Selet the Instance Type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.micro 
      - t2.medium   

Resources:
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
  
  EIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Instance