AWSTemplateFormatVersion: 2010-09-09

Parameters:

  MyKeyName:
    Description: Select you keypair
    Type: AWS::EC2::KeyPair::KeyName
        
  EnvironmentName:
    Description: Select the Environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod

Mappings:

  MyRegionMap:
    us-east-1:
      HVM64: ami-0b69ea66ff7391e80
    us-east-2:
      HVM64: ami-00c03f7f7f2ec15c3
    ap-south-1:
      HVM64: ami-0cb0e70f44e1a4bb5

  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    uat:
      instanceType: t2.small
    prod:
      instanceType: t2.medium

Conditions:
  CreateEIPForProd: !Equals [!Ref EnvironmentName, prod]
  DevCreateSecurityGroup: !Equals [!Ref EnvironmentName, dev]

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64 
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: !If [DevCreateSecurityGroup, [!Ref DevInstanceSecurityGroup], !Ref 'AWS::NoValue']

  ProdEIPAddress:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Properties:
      InstanceId: !Ref EC2Instance

  DevInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Condition: DevCreateSecurityGroup
    Properties:
      GroupDescription: Allow SSH to client host DEV SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0