AWSTemplateFormatVersion: 2010-09-09
Parameters:

  MyKeyName:
    Description: Select you keypair
    Type: 'AWS::EC2::KeyPair::KeyName'

  EnvironmentName:
    Description: Select the Environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod

Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-0b69ea66ff7391e80
    us-east-2:
      HVM64: ami-00c03f7f7f2ec15c3
    ap-south-1:
      HVM64: ami-0a74bfeb190bd404f

  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    uat:
      instanceType: t2.small
    prod:
      instanceType: t2.medium

Conditions:
  DevSecurityGroupCreation: !Equals [!Ref EnvironmentName, dev]

Metadata:

  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: EC2 Instance Configuration & Environment
        Parameters:
          - MyKeyName
          - EnvironmentName
    ParameterLabels:
      EnvironmentName:
        defaults: Choose the Environment to run
      MyKeyName:
        defaults: Choose the KeyName

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap 
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap 
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: !If [DevSecurityGroupCreation, [!Ref DevInstanceSecurityGroup], !Ref 'AWS::NoValue']
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum localinstall --nogpgcheck http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
          sudo yum localinstall --nogpgcheck http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
          sudo yum install httpd* -y
          sudo systemctl start httpd
          
  DevInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Condition: DevSecurityGroupCreation
    Properties:
      GroupDescription: Allow SSH to client host DEV SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          
Outputs:

  MyInstanceID:
    Description: My Instance ID
    Value: !Ref EC2Instance

  MyInstancePublicDNS:
    Description: My Instance MyInstancePublicDNS
    Value: !GetAtt EC2Instance.PublicDnsName

  MyInstancePrivateDNS:
    Description: My Instance MyInstancePrivateDNS
    Value: !GetAtt EC2Instance.PrivateDnsName

  MyInstanceAvailabilityZone:
    Description: My Instance AZ
    Value: !GetAtt EC2Instance.AvailabilityZone
    Export:
      Name: !Sub '${AWS::StackName}-InstanceAvaiavleZone'

  MyInstanceSecurityGroup:
    Description: Security Group Id
    Value: !Ref DevInstanceSecurityGroup
    Condition: DevSecurityGroupCreation
    Export:
      Name: !Join ["-", [!Ref 'AWS::StackName', MyInstanceSG]]
