AWSTemplateFormatVersion: 2010-09-09
Parameters:
 
  MyKeyName:
    Description: Select you keypair
    Type: 'AWS::EC2::KeyPair::KeyName'

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      Comment: Deploy a simple tomcat application
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              java-1.8.0-openjdk.x86_64: []
              jdva-1.8.0-openjdk-devel: []
              tomcat8: []
          groups:
            prodgroup: {}
            devgroup:
              gid: "5001"
          users:
          sources:
          files:
          commands:
          services:
    Properties:
      ImageId: ami-02913db388613c3e1
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups: 
        - !Ref DevInstanceSecurityGroup
          
  DevInstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH to client host DEV SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          
Outputs:

  MyInstanceID:
    Description: My Instance ID
    Value: !Ref EC2Instance
