version: 0.2

environment_variable:
  plaintext:
    TEMPLATE_FILES: |
      vpc-dev.yml
      vpc-prod.yml
    CONFIG_FILES: |
      vpc-dev-config.json
      vpc-prod-config.json
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      npm install jsonlint -g
  pre_build:
    commands:
      - echo "Validating CFN templates"
      - |
        for cfn_template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done
      - |
        for conf in $CONFIG_FILES; do
          echo "Validating CFN parameters config file $conf"
          jsonlint -q $conf
        done
  build:      
    commands:
      - echo "do nothing"
artifacts:
  files:
    - vpc-dev.yml
    - vpc-dev-config.json
    - vpc-prod.yml
    - vpc-prod-config.json